#!/usr/bin/env node
import { readFile, writeFile } from 'fs/promises';
import { resolve } from 'path';

const ROOT = resolve('.');
const SRC_DIR = resolve(ROOT, 'src');

async function writeVersionFile() {
  const pkgPath = resolve(ROOT, 'package.json');
  const pkgRaw = await readFile(pkgPath, 'utf8');
  const pkg = JSON.parse(pkgRaw);
  const versionModule = `export const VERSION = ${JSON.stringify(pkg.version)};\n`;
  const versionPath = resolve(SRC_DIR, 'version.ts');
  const prev = await readFile(versionPath, 'utf8').catch(() => null);
  if (prev !== versionModule) {
    await writeFile(versionPath, versionModule, 'utf8');
  }
}

function toDataModule(base64) {
  return `/**
 * Auto-generated by scripts/prebuild.mjs
 * DO NOT EDIT MANUALLY.
 */
export const PORTAL_POSE_WASM_BASE64 = '${base64}';

let cachedBinary: Uint8Array | null = null;

export function getPortalPoseWasmBinary(): Uint8Array {
  if (!cachedBinary) {
    let binaryString: string;
    if (typeof atob === 'function') {
      binaryString = atob(PORTAL_POSE_WASM_BASE64);
    } else {
      const nodeBuffer = (globalThis as { Buffer?: { from: (input: string, encoding: string) => { toString: (enc: string) => string } } }).Buffer;
      if (!nodeBuffer) {
        throw new Error('No base64 decoder available in this environment.');
      }
      binaryString = nodeBuffer
        .from(PORTAL_POSE_WASM_BASE64, 'base64')
        .toString('binary');
    }
    const len = binaryString.length;
    cachedBinary = new Uint8Array(len);
    for (let i = 0; i < len; i += 1) {
      cachedBinary[i] = binaryString.charCodeAt(i);
    }
  }
  return cachedBinary;
}

export function getPortalPoseWasmDataURL(): string {
  return 'data:application/wasm;base64,' + PORTAL_POSE_WASM_BASE64;
}
`;
}

async function writePortalPoseEmbed() {
  const wasmPath = resolve(SRC_DIR, 'wasm', 'portal-pose', 'portal_pose.wasm');
  const wasmBuffer = await readFile(wasmPath);
  const base64 = wasmBuffer.toString('base64');
  const moduleSource = toDataModule(base64);
  const modulePath = resolve(
    SRC_DIR,
    'wasm',
    'portal-pose',
    'portal_pose_embed.ts',
  );
  const prev = await readFile(modulePath, 'utf8').catch(() => null);
  if (prev !== moduleSource) {
    await writeFile(modulePath, moduleSource, 'utf8');
  }
}

await Promise.all([writeVersionFile(), writePortalPoseEmbed()]);
