#!/usr/bin/env node
import { readFile, writeFile } from 'fs/promises';
import { resolve } from 'path';

const ROOT = resolve('.');
const SRC_DIR = resolve(ROOT, 'src');
const NODE_MODULES_DIR = resolve(ROOT, 'node_modules');

const EMBEDDED_ASSET_CONFIG = [
  {
    target: 'runtime/fonts/inter/Inter-Latin-Variable.woff2',
    source: resolve(
      ROOT,
      'immersive-web-emulator',
      'assets',
      'fonts',
      'inter',
      'Inter-Latin-Variable.woff2',
    ),
    mime: 'font/woff2',
  },
  {
    target: 'runtime/mediapipe/tasks-vision/wasm/vision_wasm_internal.js',
    source: resolve(
      NODE_MODULES_DIR,
      '@mediapipe',
      'tasks-vision',
      'wasm',
      'vision_wasm_internal.js',
    ),
    mime: 'application/javascript',
  },
  {
    target: 'runtime/mediapipe/tasks-vision/wasm/vision_wasm_internal.wasm',
    source: resolve(
      NODE_MODULES_DIR,
      '@mediapipe',
      'tasks-vision',
      'wasm',
      'vision_wasm_internal.wasm',
    ),
    mime: 'application/wasm',
  },
  {
    target: 'runtime/mediapipe/tasks-vision/wasm/vision_wasm_nosimd_internal.js',
    source: resolve(
      NODE_MODULES_DIR,
      '@mediapipe',
      'tasks-vision',
      'wasm',
      'vision_wasm_nosimd_internal.js',
    ),
    mime: 'application/javascript',
  },
  {
    target: 'runtime/mediapipe/tasks-vision/wasm/vision_wasm_nosimd_internal.wasm',
    source: resolve(
      NODE_MODULES_DIR,
      '@mediapipe',
      'tasks-vision',
      'wasm',
      'vision_wasm_nosimd_internal.wasm',
    ),
    mime: 'application/wasm',
  },
  {
    target: 'runtime/mediapipe/models/face_landmarker/face_landmarker.task',
    source: resolve(
      ROOT,
      'immersive-web-emulator',
      'assets',
      'mediapipe',
      'models',
      'face_landmarker',
      'face_landmarker.task',
    ),
    mime: 'application/octet-stream',
  },
];

async function writeVersionFile() {
  const pkgPath = resolve(ROOT, 'package.json');
  const pkgRaw = await readFile(pkgPath, 'utf8');
  const pkg = JSON.parse(pkgRaw);
  const versionModule = `export const VERSION = ${JSON.stringify(pkg.version)};\n`;
  const versionPath = resolve(SRC_DIR, 'version.ts');
  const prev = await readFile(versionPath, 'utf8').catch(() => null);
  if (prev !== versionModule) {
    await writeFile(versionPath, versionModule, 'utf8');
  }
}

function toDataModule(base64) {
  return `/**
 * Auto-generated by scripts/prebuild.mjs
 * DO NOT EDIT MANUALLY.
 */
export const PORTAL_POSE_WASM_BASE64 = '${base64}';

let cachedBinary: Uint8Array | null = null;

export function getPortalPoseWasmBinary(): Uint8Array {
  if (!cachedBinary) {
    let binaryString: string;
    if (typeof atob === 'function') {
      binaryString = atob(PORTAL_POSE_WASM_BASE64);
    } else {
      const nodeBuffer = (globalThis as { Buffer?: { from: (input: string, encoding: string) => { toString: (enc: string) => string } } }).Buffer;
      if (!nodeBuffer) {
        throw new Error('No base64 decoder available in this environment.');
      }
      binaryString = nodeBuffer
        .from(PORTAL_POSE_WASM_BASE64, 'base64')
        .toString('binary');
    }
    const len = binaryString.length;
    cachedBinary = new Uint8Array(len);
    for (let i = 0; i < len; i += 1) {
      cachedBinary[i] = binaryString.charCodeAt(i);
    }
  }
  return cachedBinary;
}

export function getPortalPoseWasmDataURL(): string {
  return 'data:application/wasm;base64,' + PORTAL_POSE_WASM_BASE64;
}
`;
}

async function writePortalPoseEmbed() {
  const wasmPath = resolve(SRC_DIR, 'wasm', 'portal-pose', 'portal_pose.wasm');
  const wasmBuffer = await readFile(wasmPath);
  const base64 = wasmBuffer.toString('base64');
  const moduleSource = toDataModule(base64);
  const modulePath = resolve(
    SRC_DIR,
    'wasm',
    'portal-pose',
    'portal_pose_embed.ts',
  );
  const prev = await readFile(modulePath, 'utf8').catch(() => null);
  if (prev !== moduleSource) {
    await writeFile(modulePath, moduleSource, 'utf8');
  }
}

function buildEmbeddedRuntimeAssetsModule(assets) {
  const assetEntries = assets
    .map(
      ({ target, mime, base64 }) =>
        `  ${JSON.stringify(target)}: {\n    mime: ${JSON.stringify(mime)},\n    base64: ${JSON.stringify(base64)}\n  }`,
    )
    .join(',\n');

  return `/**
 * Auto-generated by scripts/prebuild.mjs
 * DO NOT EDIT MANUALLY.
 */
type EmbeddedAssetDescriptor = {
  mime: string;
  base64: string;
  dataUrl?: string;
  bytes?: Uint8Array;
  objectUrl?: string | null;
};

const EMBEDDED_ASSETS: Record<string, EmbeddedAssetDescriptor> = {
${assetEntries}
};

type NodeBufferFactory = {
  from: (input: string, encoding: string) => { length: number; [index: number]: number };
};

function decodeBase64Chunk(base64: string): Uint8Array {
  if (typeof atob === 'function') {
    const binary = atob(base64);
    const length = binary.length;
    const bytes = new Uint8Array(length);
    for (let i = 0; i < length; i += 1) {
      bytes[i] = binary.charCodeAt(i);
    }
    return bytes;
  }
  const nodeBuffer = (globalThis as { Buffer?: NodeBufferFactory }).Buffer;
  if (!nodeBuffer) {
    throw new Error('Embedded runtime assets require a base64 decoder.');
  }
  const buffer = nodeBuffer.from(base64, 'base64');
  const bytes = new Uint8Array(buffer.length);
  for (let i = 0; i < buffer.length; i += 1) {
    bytes[i] = buffer[i];
  }
  return bytes;
}

function ensureBytes(asset: EmbeddedAssetDescriptor): Uint8Array {
  if (!asset.bytes) {
    asset.bytes = decodeBase64Chunk(asset.base64);
  }
  return asset.bytes;
}

function ensureDataUrl(asset: EmbeddedAssetDescriptor): string {
  if (!asset.dataUrl) {
    asset.dataUrl = 'data:' + asset.mime + ';base64,' + asset.base64;
  }
  return asset.dataUrl;
}

type UrlCreator = {
  createObjectURL?: (blob: Blob) => string;
};

function getUrlCreator(): UrlCreator | null {
  const globalUrl = (globalThis as { URL?: UrlCreator; webkitURL?: UrlCreator }) || {};
  if (globalUrl.URL?.createObjectURL) {
    return globalUrl.URL;
  }
  if (globalUrl.webkitURL?.createObjectURL) {
    return globalUrl.webkitURL;
  }
  return null;
}

function ensureObjectUrl(asset: EmbeddedAssetDescriptor, mimeOverride?: string): string | null {
  if (asset.objectUrl) {
    return asset.objectUrl;
  }
  const creator = getUrlCreator();
  if (!creator || typeof Blob === 'undefined') {
    asset.objectUrl = ensureDataUrl(asset);
    return asset.objectUrl;
  }
  const bytes = ensureBytes(asset);
  // Create a fresh ArrayBuffer to satisfy TS5 BlobPart type requirements
  const arrayBuffer = new ArrayBuffer(bytes.byteLength);
  new Uint8Array(arrayBuffer).set(bytes);
  const blob = new Blob([arrayBuffer], { type: mimeOverride ?? asset.mime });
  asset.objectUrl = creator.createObjectURL?.(blob) ?? null;
  if (!asset.objectUrl) {
    asset.objectUrl = ensureDataUrl(asset);
  }
  return asset.objectUrl;
}

function getAsset(path: string): EmbeddedAssetDescriptor | null {
  return EMBEDDED_ASSETS[path] ?? null;
}

export function resolveEmbeddedRuntimeAssetDataUrl(relativePath: string): string | null {
  const asset = getAsset(relativePath);
  if (!asset) {
    return null;
  }
  return ensureDataUrl(asset);
}

export type EmbeddedWasmFileset = {
  wasmLoaderPath: string;
  wasmBinaryPath: string;
  assetLoaderPath?: string;
  assetBinaryPath?: string;
};

type VisionVariant = 'simd' | 'nosimd';

function resolveVariantAssets(variant: VisionVariant): {
  loader: EmbeddedAssetDescriptor;
  wasm: EmbeddedAssetDescriptor;
} | null {
  const suffix = variant === 'simd' ? 'vision_wasm_internal' : 'vision_wasm_nosimd_internal';
  const loader = getAsset('runtime/mediapipe/tasks-vision/wasm/' + suffix + '.js');
  const wasm = getAsset('runtime/mediapipe/tasks-vision/wasm/' + suffix + '.wasm');
  if (!loader || !wasm) {
    return null;
  }
  return { loader, wasm };
}

let cachedSimdFileset: EmbeddedWasmFileset | null = null;
let cachedNoSimdFileset: EmbeddedWasmFileset | null = null;

export function getEmbeddedVisionWasmFileset(variant: VisionVariant): EmbeddedWasmFileset | null {
  if (variant === 'simd' && cachedSimdFileset) {
    return cachedSimdFileset;
  }
  if (variant === 'nosimd' && cachedNoSimdFileset) {
    return cachedNoSimdFileset;
  }
  const descriptors = resolveVariantAssets(variant);
  if (!descriptors) {
    return null;
  }
  const loaderUrl = ensureObjectUrl(descriptors.loader, 'application/javascript');
  const wasmUrl = ensureObjectUrl(descriptors.wasm, 'application/wasm');
  if (!loaderUrl || !wasmUrl) {
    return null;
  }
  const fileset: EmbeddedWasmFileset = {
    wasmLoaderPath: loaderUrl,
    wasmBinaryPath: wasmUrl,
  };
  if (variant === 'simd') {
    cachedSimdFileset = fileset;
  } else {
    cachedNoSimdFileset = fileset;
  }
  return fileset;
}

let cachedFaceModelUrl: string | null | undefined;

export function getEmbeddedFaceLandmarkerModelUrl(): string | null {
  if (cachedFaceModelUrl !== undefined) {
    return cachedFaceModelUrl;
  }
  const model = getAsset('runtime/mediapipe/models/face_landmarker/face_landmarker.task');
  cachedFaceModelUrl = model ? ensureDataUrl(model) : null;
  return cachedFaceModelUrl;
}
`;
}

async function writeEmbeddedRuntimeAssets() {
  const assets = [];
  for (const config of EMBEDDED_ASSET_CONFIG) {
    const buffer = await readFile(config.source);
    assets.push({ ...config, base64: buffer.toString('base64') });
  }
  const moduleSource = buildEmbeddedRuntimeAssetsModule(assets);
  const outputPath = resolve(SRC_DIR, 'runtime', 'EmbeddedRuntimeAssets.ts');
  const previous = await readFile(outputPath, 'utf8').catch(() => null);
  if (previous !== moduleSource) {
    await writeFile(outputPath, moduleSource, 'utf8');
  }
}

await Promise.all([writeVersionFile(), writePortalPoseEmbed(), writeEmbeddedRuntimeAssets()]);
