import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, extname } from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const ASSETS = [
  {
    name: 'ASSET_WATERMARK',
    path: '../assets/watermark/portal_watermark.png',
    mime: 'image/png',
  },
  {
    name: 'ASSET_ICON_HELP',
    path: '../assets/icons/ic_feathericons_help_circle.svg',
    mime: 'image/svg+xml',
  },
  {
    name: 'ASSET_ICON_SETTINGS',
    path: '../assets/icons/ic_feathericons_settings.svg',
    mime: 'image/svg+xml',
  },
  {
    name: 'ASSET_MODE_2D',
    path: '../assets/mode/mode_2d.png',
    mime: 'image/png',
  },
  {
    name: 'ASSET_MODE_3D',
    path: '../assets/mode/mode_3d.png',
    mime: 'image/png',
  },
];

const outDir = resolve(__dirname, '../src/generated');
const outFile = resolve(outDir, 'assets.ts');

await mkdir(outDir, { recursive: true });

const lines = [
  '// Auto-generated by scripts/generate-assets.mjs. Do not edit manually.',
];

const encode = (buffer) => buffer.toString('base64');

for (const asset of ASSETS) {
  const sourcePath = resolve(__dirname, asset.path);
  let buffer;
  if (asset.mime === 'image/svg+xml') {
    let svg = await readFile(sourcePath, 'utf8');
    svg = svg
      .replace(/stroke="#000000"/g, 'stroke="rgba(76, 99, 182, 0.8)"')
      .replace(/stroke="currentColor"/g, 'stroke="rgba(76, 99, 182, 0.8)"');
    buffer = Buffer.from(svg, 'utf8');
  } else {
    buffer = await readFile(sourcePath);
  }
  const base64 = encode(buffer);
  const dataUri = `data:${asset.mime};base64,${base64}`;
  lines.push(`export const ${asset.name} = ${JSON.stringify(dataUri)};`);
}

lines.push('');

await writeFile(outFile, lines.join('\n'));
